language: erlang

sudo: false
os: linux
otp_release:
  - 21.0.2
  - 20.3.8.8
  - 19.3
  - 18.3
  - 17.5
  - R16B03-1
  - R15B03

script:
  - ./rebar3 as prod compile
  # - ./rebar3 as check xref
  # - ./rebar3 as check dialyzer
  - ./rebar3 eunit
  - ./rebar3 edoc
